### PR TITLE
Add new Discovery/FUZZ

### PR DESCRIPTION
**Pull request by riza**

### CODE REVIEW

**Comment by riza** [comment]
?

**Comment by hahwul** [comment]
Hi @riza ,
I was a little late checking if it was actually useful and if there was a code that could cause other problems. I'm sure you understand. thank you for PR :D

Cheers!

**Comment by riza** [comment]
Hi @hahwul ,

No problem, thanks for merge. :)

**Comment by hahwul** [comment]
@riza 
I just added your name to thanks on footer. If you need a change link(e,g twitter or any other link), tell me!
(Currently, your github user page)

**Comment by riza** [comment]
Thanks! :)

**Pull request merged**
